# Server configuration
server:
  port: ${SERVER_PORT}

# Importing the .env
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: grupo48-telemed
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    url: jdbc:${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS

aws:
  cognito:
    userPoolId: ${AWS_USER_POOL_ID}
    clientId: ${AWS_CLIENT_ID}
    clientSecret: ${AWS_CLIENT_SECRET}
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}

logging:
  level:
    org.hibernate: ${LOG_LEVEL}
    root: ${LOG_LEVEL}
    org.springframework: ${LOG_LEVEL}
  file:
    name: ${LOG_PATH}

# Configuration for OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
    title: Telemed API
    description: API para o Hackathon da FIAP - 4SOAT - Grupo 48
  swagger-ui:
    path: /swagger-ui-custom.html

